# EPIC_MAP is only for confirmed IG EPIC codes.
# Do not guess these. Wrong EPICs cause IG 403/404 errors.
EPIC_MAP = {
    "BTC": "CS.D.BITCOIN.CFD.IP",
    "ETH": "CS.D.ETHUSD.CFD.IP",
}

# Finnhub symbols used for current price display.
PRICE_SYMBOL_MAP = {
    "SPY": "SPY",
    "QQQ": "QQQ",
    "DIA": "DIA",
    "IWM": "IWM",
    "GLD": "GLD",
    "USO": "USO",
    "UAL": "UAL",
    "NFLX": "NFLX",
    "AA": "AA",
    "STLD": "STLD",
    "IBKR": "IBKR",
    "APLD": "APLD",
    "TSLA": "TSLA",
    "IBM": "IBM",
    "INTC": "INTC",
    "AXP": "AXP",
    "UHS": "UHS",
    "LUMN": "LUMN",
    "SBUX": "SBUX",
    "QCOM": "QCOM",
    "RIVN": "RIVN",
    "META": "META",
    "AMZN": "AMZN",
    "GOOGL": "GOOGL",
    "HIMS": "HIMS",
    "MARA": "MARA",
    "ONON": "ONON",
    "CSCO": "CSCO",
    "AMAT": "AMAT",
    "NU": "NU",
    "BTC": "BINANCE:BTCUSDT",
    "ETH": "BINANCE:ETHUSDT",
}

# IG search terms used only when placing demo trades or finding IG markets.
IG_SEARCH_MAP = {
    "BTC": "Bitcoin",
    "ETH": "Ethereum",
    "SPY": "SPDR S&P 500 ETF",
    "QQQ": "Invesco QQQ Trust",
    "DIA": "SPDR Dow Jones Industrial Average ETF",
    "IWM": "iShares Russell 2000 ETF",
    "GLD": "SPDR Gold Shares",
    "USO": "United States Oil Fund",
    "UAL": "United Airlines Holdings",
    "NFLX": "Netflix",
    "AA": "Alcoa",
    "STLD": "Steel Dynamics",
    "IBKR": "Interactive Brokers",
    "APLD": "Applied Digital",
    "TSLA": "TSLA",
    "IBM": "IBM",
    "INTC": "Intel",
    "AXP": "American Express",
    "UHS": "Universal Health Services",
    "LUMN": "Lumen Technologies",
    "SBUX": "Starbucks",
    "QCOM": "Qualcomm",
    "RIVN": "Rivian",
    "META": "META",
    "AMZN": "AMZN",
    "GOOGL": "GOOGL",
    "HIMS": "HIMS",
    "MARA": "MARA",
    "ONON": "ONON",
    "CSCO": "CSCO",
    "AMAT": "AMAT",
    "NU": "NU",
}
